#!/usr/bin/env bash
# This loops from 1 till 10 and displays
# "bad luck" on iteration 4
# "good luck" on iteration 8
# "Best Schhol" for the rest

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
