#!/usr/bin/env bash
# Display number 1 till 20 and also
# "bad luck from China" on iteration 4
# "bad luck from Japan" on iteration 9
# "bad luck from Italy" on iteration 17

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
